import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { AuthProvider, useAuth } from "@/components/ui/AuthProvider";
import { getCurrentUser, getUser } from "@/lib/user";
import { SocketProvider } from "@/contexts/ws-context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

return (
  <html lang="en">
    <body
      className={`w-screen h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <AuthProvider>
        {user ? (
          <SocketProvider userId={user.id}>
            <Header />
            {children}
          </SocketProvider>
        ) : (
          <>
            <Header />
            {children}
          </>
        )}
      </AuthProvider>
    </body>
  </html>
);
}
